services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: always
    networks:
      - kizuna_network

  python-scraper:
    build:
      context: ./scrapper
      dockerfile: Dockerfile
    image: python-scraper
    container_name: python_scraper
    depends_on:
      - ollama
    ports:
      - "8000:8000"
    volumes:
      - ./scrapper:/home/appuser/app
    environment:
      OLLAMA_HOST: http://ollama:11434
      OLLAMA_MODEL: deepseek-r1:1.5b
    restart: always
    networks:
      - kizuna_network

  springboot-app:
    build:
      context: ./springboot-app
      dockerfile: Dockerfile
    image: springboot-app
    container_name: springboot_app
    depends_on:
      - ollama
      - python-scraper
      - mongo
    ports:
      - "8080:8080"
    volumes:
      - ./springboot-app:/app
    environment:
      OLLAMA_HOST: http://ollama:11434
      PYTHON_SCRAPER_HOST: http://python_scraper:8000
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/kizunacopilot
    restart: always
    networks:
      - kizuna_network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always
    networks:
      - kizuna_network

volumes:
  ollama_data:
  mongo_data:

networks:
  kizuna_network:
    driver: bridge
