python.scraper.host=${PYTHON_SCRAPER_HOST:http://localhost:8000}
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/kizunacopilot}
spring.mvc.async.request-timeout=600000
server.tomcat.connection-timeout=600000

# Observability - Actuator
management.endpoints.web.exposure.include=health,prometheus,info,metrics
management.endpoint.health.show-details=always
management.metrics.tags.application=kizuna-copilot-api

# Logging
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - [%X{traceId:-}, %X{spanId:-}] - %msg%n
logging.level.com.mrpunkdasilva.kizunacopilot=DEBUG
logging.level.org.springframework.web=INFO